version: '3.8'

services:
  web:
    image: ghcr.io/your-username/phone-investigation-system:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/phone_investigation_staging
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=staging
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=phone_investigation_staging
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data_staging:/data

volumes:
  postgres_data_staging:
  redis_data_staging:
